name: First action
on: push

jobs:
    first_test1:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: welcome message
              run: |
                echo "My first github action"
                ls
                cat README.md


